# Generated by Django 6.0 on 2025-12-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='endereco_cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='endereco_estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='endereco_pais',
            field=models.CharField(default='Brasil', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='endereco_rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
